### ISSUE TITLE
Uploader Glitches when uploading large audio files

### ISSUE THREAD

**Issue by DREWNOLT** [SheepTester/sheeptester.github.io#16]
When trying to upload an audio file that was 30 MB, the upload input glitched; for a second it showed the name of the file, but then switched back to the "No File Chosen" Text.

**Comment by SheepTester** [comment]
I don't think it's meant to handle large audio files. Was there an error in the console?

**Comment by DREWNOLT** [comment]
IDK, I use a Chromebook, and my parents blocked inspect, and the browser console.
