### ISSUE TITLE
[BUG] 2048 Doesn't seem to work

### ISSUE THREAD

**Issue by Darker-Ink** [SheepTester/sheeptester.github.io#18]
using 
`javascript:(t=>{var s=document.createElement(t);s.type='text/java'+t;s.src='https://sheeptester.github.io/javascripts/2048.js';document.body.appendChild(s);})('script')`

it doesn't seem to work maybe I'm doing something wrong?

**Comment by SheepTester** [comment]
It doesn't work on all websites because some websites do not allow adding <script> tags that link to external scripts for security reasons

**Comment by Darker-Ink** [comment]
> It doesn't work on all websites because some websites do not allow adding <script> tags that link to external scripts for security reasons

Ahhh yes yes that makes more sense alright alright thank you
