### ISSUE TITLE
just gonna fork opencrap and make some alterations

### ISSUE THREAD

**Issue by bacc-studio** [SheepTester/sheeptester.github.io#20]
if i have your permission

**Comment by SheepTester** [comment]
The repository is licensed under the MIT license, so you don't need my permission. Also, GitHub's TOS allows you to fork any public repository without asking for permission first

So sure, feel free to fork OpenShit

**Comment by nickpythonluajava** [comment]
this is bacc-studio's main gh account

when i publish it to pages I cant do anything except open video files that literally don't open the file

**Comment by nickpythonluajava** [comment]
here's the site
bacc-studio.github.io

**Comment by SheepTester** [comment]
Always check the console for errors

![image](https://user-images.githubusercontent.com/22133785/117550996-2c9a6c00-aff8-11eb-8af7-1f8cee7eb5dd.png)

I believe OpenShit uses dependencies from elsewhere in this repo
