### ISSUE TITLE
OpenShit things

### ISSUE THREAD

**Issue by bacc-studio** [SheepTester/sheeptester.github.io#21]
so i got the local html version to work but i didnt get it to work when i published it on pages why does this happen?

i posted here because i couldnt find my original issue and i couldnt find any solutions on the internet

**Comment by bacc-studio** [comment]
i've been trying to fix this for 2 hours

**Comment by SheepTester** [comment]
Your original issue is at #20; maybe see https://github.com/SheepTester/sheeptester.github.io/issues/20#issuecomment-835481294?

You should check the console to see if there are any errors

**Comment by nickpythonluajava** [comment]
i checked there were

**Comment by SheepTester** [comment]
What do the errors say?

**Comment by nickpythonluajava** [comment]
i think it was like elem is not defined or something

**Comment by nickpythonluajava** [comment]
i tried editing the index.html to other things too but it dont work

**Comment by SheepTester** [comment]
I believe OpenShit has a dependency on /js/_dom2.js:

https://github.com/SheepTester/sheeptester.github.io/blob/2dd34246e63f156cecc739fbc2e93be32a99f4fb/javascripts/video/shit/index.html#L11-L12

Make sure they load properly

**Comment by nickpythonluajava** [comment]
it is in the folder or repo or something

**Comment by nickpythonluajava** [comment]
i loaded it correctly on the index.html on my computer (local file)

**Comment by nickpythonluajava** [comment]
oh so i just rename it and edit the index file and everything should work fine?

**Comment by bacc-studio** [comment]
so i did and everyting worked all of a suden i just had to do THAT and it took me 3 hours to try to fix. closing
