### ISSUE TITLE
The Call of the Coders!

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/sheeptester.github.io#25]
### Hi!
 This is The Call of the Coders! (not Call of the Wild XD) , and it's [SparkScratch-P](https://sparkscratch-p.github.io/) Here! Hope u recognize ur great fan!!!!

 I, on Behalf or App-apocalypse, am here to notify you that, I have promoted you to the owner of the organization. Can you please help in organizing the team professionally, and its pages look better, or build a few Apps for it? 

## Will wait for your cooperation

Thanking you,
I remain, 
your fan,
SparkScratch-P

**Comment by SheepTester** [comment]
Not related to the repository, closing
