### ISSUE TITLE
Did you try using a custom domain (In the pages tab)?

### ISSUE THREAD

**Issue by EnderKitty95** [SheepTester/sheeptester.github.io#30]

**Comment by SheepTester** [comment]
What for?

**Comment by EnderKitty95** [comment]
You can customize the name and move it out of a github subdomain (Eg.
example.com)

**Comment by SheepTester** [comment]
Domains expire if not paid for. I want links to my website to always work, even after I die. Using *.github.io is more reliable, and also subtly indicates that the website may have an open source repository on GitHub.

**Comment by EnderKitty95** [comment]
Ok
