### ISSUE TITLE
Project Speed

### ISSUE THREAD

**Issue by humphreygaming** [SheepTester/sheeptester.github.io#9]
The project downloaded seems to run way to fast, even worse with turbo mode enabled

**Comment by SheepTester** [comment]
I'm assuming you're talking about the HTMLifier. Did you leave compatibility mode on? Compatibility mode forces Scratch to run at 30 fps; turning it off allows your project to run at 60 fps or faster, which can make frame-rate dependent scripts run twice as fast.

**Comment by SheepTester** [comment]
I'm assuming this is resolved
